name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy

    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Build
      run: wasm-pack build --target bundler

    - name: Run tests
      run: wasm-pack test --headless --chrome
